services:
  mysql:
    image: mysql:latest
    container_name: event_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword

    ports:
      - "3006:3306"
    # volumes:
    #   - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: event_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "9000:80"

# volumes:
#   mysql_data:
 